[phases.setup]
nixPkgs = ['nodejs-18_x', 'openssl']

[phases.install]
cmds = [
  'npm install',
  'cd apps/backend && npm install',
  'cd apps/backend && npx prisma generate'
]

[phases.build]
cmds = [
  'cd apps/backend && npm run build',
  'cd apps/backend && ls -la dist',
  'cd apps/backend && ls -la dist/src'
]

[start]
cmd = 'cd apps/backend && npm run start:prod'