#!/bin/bash

# Script para configurar GitHub Secrets
# Execute este script após adicionar os secrets manualmente no GitHub

echo "🔐 Configuração de Secrets para GitHub Actions"
echo "============================================="
echo ""
echo "📋 Adicione os seguintes secrets no GitHub:"
echo "   Repositório: https://github.com/MuriloM676/PaneladeCasa"
echo "   Caminho: Settings > Secrets and variables > Actions"
echo ""
echo "✅ SECRETS PARA ADICIONAR:"
echo ""
echo "1. VERCEL_TOKEN"
echo "   Value: eMlDyDb3wKBs26TI26oqpWr1"
echo ""
echo "2. RAILWAY_TOKEN"
echo "   Value: fb038fd3-9e82-47f5-ac51-8ed99cbef3b6"
echo ""
echo "3. VERCEL_ORG_ID"
echo "   Value: team_BJ8zMMsVKECY4AlzlHqyYzGC"
echo ""
echo "4. VERCEL_PROJECT_ID"
echo "   Value: prj_J8JCIlk8bHad7zD2F5U5RQXqbUBS"
echo ""
echo "5. NEXT_PUBLIC_API_URL (será definido após Railway deploy)"
echo "   Value: https://[seu-backend].railway.app"
echo ""
echo "🚀 PRÓXIMOS PASSOS:"
echo "1. Adicionar os 4 primeiros secrets no GitHub"
echo "2. Configurar projeto no Railway"
echo "3. Adicionar NEXT_PUBLIC_API_URL com a URL do Railway"
echo "4. Fazer merge da branch para main"
echo "5. Pipeline será executado automaticamente!"
echo ""
echo "📖 Para mais detalhes, consulte: docs/CI_CD_SETUP.md"